"""Static checks for the Workstream C.2 core chat panel UX."""

from __future__ import annotations

from pathlib import Path
import unittest


REPO_ROOT = Path(__file__).resolve().parents[2]
EDITOR_MODULE = REPO_ROOT / "unreal_plugin" / "Source" / "UnrealMCPEditor"
PANEL_CPP = EDITOR_MODULE / "Private" / "MCPChatPanel.cpp"
PANEL_H = EDITOR_MODULE / "Public" / "MCPChatPanel.h"
BUILD_CS = EDITOR_MODULE / "UnrealMCPEditor.Build.cs"


class CoreChatPanelUxTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.cpp = PANEL_CPP.read_text(encoding="utf-8")
        cls.header = PANEL_H.read_text(encoding="utf-8")
        cls.build_cs = BUILD_CS.read_text(encoding="utf-8")

    def test_two_pane_composer_layout_and_key_handling(self) -> None:
        self.assertIn("SNew(SSplitter)", self.cpp)
        self.assertIn(".Orientation(Orient_Vertical)", self.cpp)
        self.assertIn("SAssignNew(MessageInput, SMultiLineEditableTextBox)", self.cpp)
        self.assertIn(".OnKeyDownHandler(this, &SMCPChatPanel::HandleComposerKeyDown)", self.cpp)
        self.assertIn("EKeys::Enter", self.cpp)
        self.assertIn("!InKeyEvent.IsShiftDown()", self.cpp)

    def test_role_tagged_message_bubbles_have_actions(self) -> None:
        for role in ("User", "Agent", "Tool"):
            with self.subTest(role=role):
                self.assertIn(role, self.cpp)

        for action in ("Copy", "Re-run", "Open Log", "Reveal Asset"):
            with self.subTest(action=action):
                self.assertIn(action, self.cpp)

        self.assertIn("BuildMessageWidget", self.header)
        self.assertIn("GetMessageColor", self.header)
        self.assertIn("NormaliseSender", self.header)

    def test_drag_drop_target_is_wired_to_composer(self) -> None:
        self.assertIn("virtual FReply OnDragOver", self.header)
        self.assertIn("virtual FReply OnDrop", self.header)
        self.assertIn("BuildDropReference", self.header)
        self.assertIn("@asset:<dropped-asset>", self.cpp)
        self.assertIn("@actor:<dropped-actor>", self.cpp)
        self.assertIn("@file:<dropped-file>", self.cpp)
        self.assertIn("const FString DropReference = BuildDropReference(Operation)", self.cpp)
        self.assertIn("InsertComposerText(DropReference)", self.cpp)

    def test_streaming_delta_path_updates_existing_text_block(self) -> None:
        self.assertIn("AppendStreamingDelta", self.header)
        self.assertIn("ApplySseLine", self.header)
        self.assertIn("StreamingMessageTextBlocks", self.header)
        self.assertIn("Line.StartsWith(TEXT(\"data:\"))", self.cpp)
        self.assertIn("EventObject->TryGetStringField(TEXT(\"delta\"), Delta)", self.cpp)
        self.assertIn("(*ExistingTextBlock)->SetText", self.cpp)

    def test_cockpit_recovery_line_renders_safe_step_failure_triage_asset_quality_and_policy(self) -> None:
        self.assertIn("NextSafeStepSummary", self.header)
        self.assertIn("FailureTriageSummary", self.header)
        self.assertIn("AssetQualitySummary", self.header)
        self.assertIn("ReadinessPolicySummary", self.header)
        self.assertIn("FailureTriageCount", self.header)
        self.assertIn("GetCockpitRecoveryText", self.header)
        self.assertIn(".Text(this, &SMCPChatPanel::GetCockpitRecoveryText)", self.cpp)
        self.assertIn("Root->TryGetObjectField(TEXT(\"next_safe_step\")", self.cpp)
        self.assertIn("Root->TryGetObjectField(TEXT(\"failure_triage\")", self.cpp)
        self.assertIn("Root->TryGetObjectField(TEXT(\"generated_asset_quality_gate\")", self.cpp)
        self.assertIn("Root->TryGetObjectField(TEXT(\"readiness_policy\")", self.cpp)
        self.assertIn("blocked_policy_count", self.cpp)
        self.assertIn("missing_gates", self.cpp)
        self.assertIn("paid_animation_generation", self.cpp)
        self.assertIn("provider_pending_count", self.cpp)
        self.assertIn("import_pending_count", self.cpp)
        self.assertIn("quality_pending_count", self.cpp)
        self.assertIn("placeholder_count", self.cpp)
        self.assertIn("Assets: {2} | Policy: {3}", self.cpp)
        self.assertIn("CockpitRecoveryText", self.cpp)

    def test_cockpit_header_prefers_clean_hud_summary_packet(self) -> None:
        self.assertIn("HudStateSummary", self.header)
        self.assertIn("HudReadinessSummary", self.header)
        self.assertIn("HudFeatureSummary", self.header)
        self.assertIn("HudNextStepSummary", self.header)
        self.assertIn("HudGenerationSummary", self.header)
        self.assertIn("HudAnimationSummary", self.header)
        self.assertIn("HudEvidenceSummary", self.header)
        self.assertIn("HudOperatorHandoffSummary", self.header)
        self.assertIn("HudBlueprintMutationSummary", self.header)
        self.assertIn("HudVisibleCardCount", self.header)
        self.assertIn("bHasHudSummary", self.header)
        self.assertIn("GetCockpitHudSummaryText", self.header)
        self.assertIn(".Text(this, &SMCPChatPanel::GetCockpitHudSummaryText)", self.cpp)
        self.assertIn("Root->TryGetObjectField(TEXT(\"hud_summary\")", self.cpp)
        self.assertIn("unreal_mcp_chat_cockpit_hud_summary.v1", self.cpp)
        self.assertIn("visible_card_count", self.cpp)
        self.assertIn("primary_blocker_preview", self.cpp)
        self.assertIn("primary_blocker_overflow_count", self.cpp)
        self.assertIn("TryGetArrayField(TEXT(\"compact_cards\")", self.cpp)
        self.assertIn("CardId == TEXT(\"readiness\")", self.cpp)
        self.assertIn("CardId == TEXT(\"feature\")", self.cpp)
        self.assertIn("CardId == TEXT(\"next_safe_step\")", self.cpp)
        self.assertIn("CardId == TEXT(\"generation\")", self.cpp)
        self.assertIn("CardId == TEXT(\"evidence\")", self.cpp)
        self.assertIn("generated_animation_provider", self.cpp)
        self.assertIn("generated_animation_target_name", self.cpp)
        self.assertIn("generated_animation_next_safe_action_id", self.cpp)
        self.assertIn("generated_animation_usage_next_operator_handoff_id", self.cpp)
        self.assertIn("CockpitHudSummaryWithAnimationText", self.cpp)
        self.assertIn("Anim: {4}", self.cpp)
        self.assertIn("next_operator_handoff_label", self.cpp)
        self.assertIn("next_operator_handoff_id", self.cpp)
        self.assertIn("next_operator_handoff_command_kind", self.cpp)
        self.assertIn("next_operator_handoff_receipt_path", self.cpp)
        self.assertIn("next_operator_handoff_safety_label", self.cpp)
        self.assertIn("HandoffSafetyLabel", self.cpp)
        self.assertIn("CockpitActionWithHandoffText", self.cpp)
        self.assertIn("Handoff: {1}", self.cpp)
        self.assertIn("blueprint_mutation_evidence_state", self.cpp)
        self.assertIn("blueprint_mutation_evidence_summary", self.cpp)
        self.assertIn("blueprint_mutation_evidence_missing_count", self.cpp)
        self.assertIn("blueprint_mutation_next_gate", self.cpp)
        self.assertIn("blueprint_mutation_next_operator_handoff_id", self.cpp)
        self.assertIn("blueprint_mutation_safety_label", self.cpp)
        self.assertIn("CockpitRecoveryWithBlueprintText", self.cpp)
        self.assertIn("BP: {4}", self.cpp)
        self.assertIn("CockpitHudSummaryText", self.cpp)
        self.assertIn("HUD: {0} | {1} | {2} | {3} | {4}", self.cpp)
        self.assertIn("CockpitHudSummaryFallback", self.cpp)

    def test_cockpit_evidence_line_renders_recording_checklist_and_policy_row(self) -> None:
        self.assertIn("EvidenceRecordingSummary", self.header)
        self.assertIn("EvidenceTargetSummary", self.header)
        self.assertIn("EvidenceTargetDetailSummary", self.header)
        self.assertIn("EvidenceReviewTargetSummary", self.header)
        self.assertIn("QueuedEvidenceTargetSummary", self.header)
        self.assertIn("RuntimeEvidenceTargetSummary", self.header)
        self.assertIn("PaidGenerationEvidenceTargetSummary", self.header)
        self.assertIn("GeneratedAssetEvidenceTargetSummary", self.header)
        self.assertIn("GeneratedAnimationEvidenceTargetSummary", self.header)
        self.assertIn("EvidenceLedgerTargetSummary", self.header)
        self.assertIn("StartTargetSummary", self.header)
        self.assertIn("StatusTargetSummary", self.header)
        self.assertIn("WorkOrderTargetSummary", self.header)
        self.assertIn("GameplayTemplateTargetSummary", self.header)
        self.assertIn("PlaceholderTargetSummary", self.header)
        self.assertIn("ResumeTargetSummary", self.header)
        self.assertIn("DashboardTargetSummary", self.header)
        self.assertIn("BlockerTargetSummary", self.header)
        self.assertIn("ReadinessTargetSummary", self.header)
        self.assertIn("ReadinessRepairTargetSummary", self.header)
        self.assertIn("PlatformPreflightTargetSummary", self.header)
        self.assertIn("LiveEditorBridgeTargetSummary", self.header)
        self.assertIn("WipPromotionTargetSummary", self.header)
        self.assertIn("BlueprintMutationTargetSummary", self.header)
        self.assertIn("BridgeWrapperTargetSummary", self.header)
        self.assertIn("TestLaneTargetSummary", self.header)
        self.assertIn("GeneratedAssetReviewTargetSummary", self.header)
        self.assertIn("GeneratedAssetLifecycleTargetSummary", self.header)
        self.assertIn("AssetLifecycleCompileTargetSummary", self.header)
        self.assertIn("GeneratedAnimationLifecycleTargetSummary", self.header)
        self.assertIn("GeneratedAnimationCompileTargetSummary", self.header)
        self.assertIn("GeneratedAssetImportTargetSummary", self.header)
        self.assertIn("GeneratedAssetQualityProofTargetSummary", self.header)
        self.assertIn("GeneratedAssetReplacementTargetSummary", self.header)
        self.assertIn("GeneratedAssetTargetSummary", self.header)
        self.assertIn("GeneratedAssetProviderTaskTargetSummary", self.header)
        self.assertIn("ProviderSpendTargetSummary", self.header)
        self.assertIn("FeatureCompletionContractTargetSummary", self.header)
        self.assertIn("QueueReviewTargetSummary", self.header)
        self.assertIn("QueueTargetSummary", self.header)
        self.assertIn("RepairTargetSummary", self.header)
        self.assertIn("RepairReviewTargetSummary", self.header)
        self.assertIn("ExecuteTargetSummary", self.header)
        self.assertIn("ExecutionReviewTargetSummary", self.header)
        self.assertIn("RuntimeReviewTargetSummary", self.header)
        self.assertIn("ReadinessRepairSummary", self.header)
        self.assertIn("WorkflowActionCount", self.header)
        self.assertIn("EnabledWorkflowActionCount", self.header)
        self.assertIn("CockpitEvidenceTextWithRecording", self.cpp)
        self.assertIn("Root->TryGetObjectField(TEXT(\"evidence_recording\")", self.cpp)
        self.assertIn("Root->TryGetObjectField(TEXT(\"readiness_repair_queue\")", self.cpp)
        self.assertIn("OutOverview.ReadinessRepairSummary", self.cpp)
        self.assertIn("next repair %s%s%s, %d action(s)", self.cpp)
        self.assertIn("record_readiness_repair_queue", self.cpp)
        self.assertIn("repair queue", self.cpp)
        self.assertIn("Root->TryGetArrayField(TEXT(\"workflow_actions\")", self.cpp)
        self.assertIn("target_evidence_context", self.cpp)
        self.assertIn("target_evidence_item", self.cpp)
        self.assertIn("target_evidence_review_context", self.cpp)
        self.assertIn("record_queued_action_evidence", self.cpp)
        self.assertIn("queued_action", self.cpp)
        self.assertIn("record_runtime_evidence", self.cpp)
        self.assertIn("record_paid_generation_evidence", self.cpp)
        self.assertIn("runtime_verification", self.cpp)
        self.assertIn("record_generated_asset_evidence", self.cpp)
        self.assertIn("record_generated_animation_evidence", self.cpp)
        self.assertIn("record_feature_completion_contract", self.cpp)
        self.assertIn("feature_completion_contract", self.cpp)
        self.assertIn("target_start_context", self.cpp)
        self.assertIn("target_status_context", self.cpp)
        self.assertIn("target_work_order_context", self.cpp)
        self.assertIn("target_gameplay_template_context", self.cpp)
        self.assertIn("target_placeholder_context", self.cpp)
        self.assertIn("target_resume_context", self.cpp)
        self.assertIn("target_dashboard_context", self.cpp)
        self.assertIn("target_blocker_resolution", self.cpp)
        self.assertIn("target_readiness_policy_context", self.cpp)
        self.assertIn("target_readiness_repair_queue_context", self.cpp)
        self.assertIn("target_platform_preflight_context", self.cpp)
        self.assertIn("target_live_editor_context", self.cpp)
        self.assertIn("target_wip_promotion_context", self.cpp)
        self.assertIn("target_blueprint_mutation_context", self.cpp)
        self.assertIn("target_bridge_wrapper_context", self.cpp)
        self.assertIn("target_test_lane_context", self.cpp)
        self.assertIn("target_generated_asset_review_context", self.cpp)
        self.assertIn("target_generated_asset_lifecycle_context", self.cpp)
        self.assertIn("compile_asset_lifecycle_manifest", self.cpp)
        self.assertIn("target_asset_lifecycle_compile_context", self.cpp)
        self.assertIn("target_generated_animation_lifecycle_context", self.cpp)
        self.assertIn("compile_generated_animation_evidence", self.cpp)
        self.assertIn("target_generated_asset_import_context", self.cpp)
        self.assertIn("target_generated_asset_quality_proof_context", self.cpp)
        self.assertIn("target_generated_asset_replacement_context", self.cpp)
        self.assertIn("target_generated_asset_provider_task_context", self.cpp)
        self.assertIn("target_generated_asset_context", self.cpp)
        self.assertIn("target_provider_spend_context", self.cpp)
        self.assertIn("target_queue_review_context", self.cpp)
        self.assertIn("target_evidence_ledger_context", self.cpp)
        self.assertIn("target_queue_context", self.cpp)
        self.assertIn("target_repair_context", self.cpp)
        self.assertIn("target_repair_review_context", self.cpp)
        self.assertIn("target_runtime_review_context", self.cpp)
        self.assertIn("target_execute_context", self.cpp)
        self.assertIn("target_execution_review_context", self.cpp)
        self.assertIn("BlockerTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetTargetSummary", self.cpp)
        self.assertIn("QueueTargetSummary", self.cpp)
        self.assertIn("RepairTargetSummary", self.cpp)
        self.assertIn("RepairReviewTargetSummary", self.cpp)
        self.assertIn("ExecuteTargetSummary", self.cpp)
        self.assertIn("ExecutionReviewTargetSummary", self.cpp)
        self.assertIn("RuntimeReviewTargetSummary", self.cpp)
        self.assertIn("EvidenceTargetSummary", self.cpp)
        self.assertIn("EvidenceTargetDetailSummary", self.cpp)
        self.assertIn("EvidenceReviewTargetSummary", self.cpp)
        self.assertIn("QueuedEvidenceTargetSummary", self.cpp)
        self.assertIn("RuntimeEvidenceTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetEvidenceTargetSummary", self.cpp)
        self.assertIn("PaidGenerationEvidenceTargetSummary", self.cpp)
        self.assertIn("GeneratedAnimationEvidenceTargetSummary", self.cpp)
        self.assertIn("EvidenceLedgerTargetSummary", self.cpp)
        self.assertIn("StartTargetSummary", self.cpp)
        self.assertIn("StatusTargetSummary", self.cpp)
        self.assertIn("WorkOrderTargetSummary", self.cpp)
        self.assertIn("GameplayTemplateTargetSummary", self.cpp)
        self.assertIn("PlaceholderTargetSummary", self.cpp)
        self.assertIn("ResumeTargetSummary", self.cpp)
        self.assertIn("DashboardTargetSummary", self.cpp)
        self.assertIn("ReadinessTargetSummary", self.cpp)
        self.assertIn("ReadinessRepairTargetSummary", self.cpp)
        self.assertIn("PlatformPreflightTargetSummary", self.cpp)
        self.assertIn("LiveEditorBridgeTargetSummary", self.cpp)
        self.assertIn("WipPromotionTargetSummary", self.cpp)
        self.assertIn("BlueprintMutationTargetSummary", self.cpp)
        self.assertIn("BridgeWrapperTargetSummary", self.cpp)
        self.assertIn("TestLaneTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetReviewTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetLifecycleTargetSummary", self.cpp)
        self.assertIn("AssetLifecycleCompileTargetSummary", self.cpp)
        self.assertIn("planned_asset_prompt_count", self.cpp)
        self.assertIn("planned_animation_prompt_count", self.cpp)
        self.assertIn("manifest_pending_count", self.cpp)
        self.assertIn("missing_future_gate_preview", self.cpp)
        self.assertIn("write_manifest_recommended", self.cpp)
        self.assertIn("GeneratedAnimationLifecycleTargetSummary", self.cpp)
        self.assertIn("GeneratedAnimationCompileTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetImportTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetQualityProofTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetReplacementTargetSummary", self.cpp)
        self.assertIn("GeneratedAssetProviderTaskTargetSummary", self.cpp)
        self.assertIn("ProviderSpendTargetSummary", self.cpp)
        self.assertIn("mesh_wallet_evidence_recorded", self.cpp)
        self.assertIn("animation_allowance_evidence_recorded", self.cpp)
        self.assertIn("explicit_usage_approval_recorded", self.cpp)
        self.assertIn("QueueReviewTargetSummary", self.cpp)
        self.assertIn("artifact_preview", self.cpp)
        self.assertIn("generated_asset", self.cpp)
        self.assertIn("generated_animation", self.cpp)
        self.assertIn("target %s%s%s%s", self.cpp)
        self.assertIn("%s, %d item(s), %d pending, %d blocked, %d recorded, %d artifact(s)%s", self.cpp)
        self.assertIn("target %d event(s), %d artifact(s)%s", self.cpp)
        self.assertIn("target %s, %d op(s), %d checklist, %d compile check(s)", self.cpp)
        self.assertIn("target %s%s, %d arg(s)", self.cpp)
        self.assertIn("%s, %d gate(s), %d evidence item(s)", self.cpp)
        self.assertIn("%s, %d signal(s), %d evidence item(s)", self.cpp)
        self.assertIn("%s, %d PIE step(s), %d proof item(s), %d recorded", self.cpp)
        self.assertIn("%s%s, %d artifact(s), %d arg(s)", self.cpp)
        self.assertIn("%s, %d artifact(s), %d PIE step(s), %d proof item(s)", self.cpp)
        self.assertIn("%s%s%s, %d gate(s), %d artifact(s)", self.cpp)
        self.assertIn("%s%s%s%s, proof %d/%d, %d missing, %d artifact(s)", self.cpp)
        self.assertIn("%s, %d policy area(s), %d missing gate(s)%s", self.cpp)
        self.assertIn("review_readiness_repair_queue", self.cpp)
        self.assertIn("next_required_command", self.cpp)
        self.assertIn("%s%s%s, %d action(s), %d blocker(s)%s%s", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_readiness_repair_queue\") && !OutOverview.ReadinessRepairTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("target %s%s%s%s%s", self.cpp)
        self.assertIn("EvidenceRequired", self.cpp)
        self.assertIn("bCanContinueOffline", self.cpp)
        self.assertIn("can_continue_offline", self.cpp)
        self.assertIn("offline ok", self.cpp)
        self.assertIn("evidence %s", self.cpp)
        self.assertIn("%s, branch %s/%s, tools %d/%d, dirty %s, bridge %s, chat %s, platform %s, wrapper %s/%s, missing %d, build %s, warnings %d/%s", self.cpp)
        self.assertIn("%s%s, bridge %s, %d gate(s), %d queued, %d executable, %d blocked, exec %s, PIE %s, %d proof", self.cpp)
        self.assertIn("dirty_promotion_focused_test_command_count", self.cpp)
        self.assertIn("dirty_promotion_evidence_review_matrix_count", self.cpp)
        self.assertIn("dirty_promotion_evidence_unresolved_count", self.cpp)
        self.assertIn("target_review_group", self.cpp)
        self.assertIn("TargetReviewGroup", self.cpp)
        self.assertIn("TargetSuffix", self.cpp)
        self.assertIn("%s, branch %s/%s, %d/%d gate(s), dirty %s%s, tracked %d, batch %d, evidence %d/%d open, tests %d, lane %d, wrapper %d, build %s/%s, refs %d, last %s", self.cpp)
        self.assertIn("%s%s, %d gate(s), %d evidence, %d op(s), %d checklist, %d compile, %d queued", self.cpp)
        self.assertIn("%s, %d/%d capability, %d command(s), schema %d/%d, %d issue(s)", self.cpp)
        self.assertIn("%s, %d offline, %d live, %d paid, %d manual, %d violation(s)", self.cpp)
        self.assertIn("%s, %s, %d policy blocker(s), %d queue(s), %d asset(s)%s", self.cpp)
        self.assertIn("%s, %s, %d complete, %d blocker(s), %d evidence, %d queue(s)%s%s", self.cpp)
        self.assertIn("%s, %s/%s, %d blocker(s), %d op(s), %d checklist, %d compile, %d evidence%s%s", self.cpp)
        self.assertIn("%s, %d asset(s), %d op(s), %d checklist/%d bridge, %d compile, %d PIE, %d evidence, %d repair%s%s%s", self.cpp)
        self.assertIn("%s, %s, %d asset(s), %d provider, %d placeholder(s), %d blocker(s)%s%s", self.cpp)
        self.assertIn("%d event(s), %d complete, %d blocker(s)%s%s", self.cpp)
        self.assertIn("%s, %d event(s), %d blocker(s), %d queued, %d evidence, %d asset(s)%s%s%s", self.cpp)
        self.assertIn("%s%s, %d asset(s), %d provider, %d import, %d quality, %d placeholder(s)", self.cpp)
        self.assertIn("%s%s, %d manifest(s), %d asset(s), %d provider, %d import, %d quality, %d placeholder, %d stage(s), %d stop", self.cpp)
        self.assertIn("%s%s%s%s%s, %d motion(s), %d pending, proof %d/%d, %d stage(s), %d paid, %d editor", self.cpp)
        self.assertIn("next_safe_action", self.cpp)
        self.assertIn("NextActionLabel", self.cpp)
        self.assertIn("NextActionState", self.cpp)
        self.assertIn("NextActionTool", self.cpp)
        self.assertIn("next %s%s via %s", self.cpp)
        self.assertIn("especially `next_safe_action`", self.cpp)
        self.assertIn("including `next_safe_action`", self.cpp)
        self.assertIn("%s%s%s%s%s, proof %d/%d, %d stage(s), %d paid, %d editor", self.cpp)
        self.assertIn("%s%s, %d gate(s), %d import, %d quality, proof %d/%d, placeholder %s", self.cpp)
        self.assertIn("%s%s, %d candidate(s), proof %d/%d, %d missing, %d gate(s), %d stage(s), import %s, ready %s", self.cpp)
        self.assertIn("%s%s%s, %d placeholder(s), %d pending, %d gate(s), %d stage(s), proof %d/%d, ready %s", self.cpp)
        self.assertIn("fallback_placeholder_available", self.cpp)
        self.assertIn("continue_with_placeholder_fallback", self.cpp)
        self.assertIn("%s%s%s, %d provider, %d gate(s), %d evidence, %d placeholder(s)%s%s", self.cpp)
        self.assertIn("mesh %s, anim %s, usage %s", self.cpp)
        self.assertIn("%s%s%s%s, %d pending, %d success, %d task id, %d download, %d import, %d stage(s), ready %s", self.cpp)
        self.assertIn("%s, %d queue(s), %d action(s), %d executable, %d blocked, %d bridge, %d evidence%s", self.cpp)
        self.assertIn("BestWorkflowPriority", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_evidence\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_evidence_requirements\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_evidence_requirements\") && !OutOverview.EvidenceReviewTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_queued_action_evidence\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_runtime_evidence\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_generated_asset_evidence\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_paid_generation_evidence\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_generated_animation_evidence\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_feature_completion_contract\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"record_feature_completion_contract\") && !OutOverview.FeatureCompletionContractTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("%s%s, %d proof gate(s), %d evidence, %d stop(s), %d artifact(s)", self.cpp)
        self.assertIn("ActionId == TEXT(\"check_readiness\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"check_readiness\") && !OutOverview.ReadinessTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_platform_preflight_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_platform_preflight_gate\") && !OutOverview.PlatformPreflightTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ready_for_platform_stability", self.cpp)
        self.assertIn("current_branch", self.cpp)
        self.assertIn("branch_role", self.cpp)
        self.assertIn("build_wrapper_status", self.cpp)
        self.assertIn("build_health", self.cpp)
        self.assertIn("last_plugin_build_warning_count", self.cpp)
        self.assertIn("last_plugin_build_warning_severity", self.cpp)
        self.assertIn("warnings %d/%s", self.cpp)
        self.assertIn("build_wrapper_missing_reference_count", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_live_editor_bridge_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_live_editor_bridge_gate\") && !OutOverview.LiveEditorBridgeTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_wip_promotion_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_wip_promotion_gate\") && !OutOverview.WipPromotionTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_blueprint_mutation_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_blueprint_mutation_gate\") && !OutOverview.BlueprintMutationTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_bridge_wrapper_coverage\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_bridge_wrapper_coverage\") && !OutOverview.BridgeWrapperTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("schema_covered_command_count", self.cpp)
        self.assertIn("schema_command_count", self.cpp)
        self.assertIn("schema %d/%d", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_test_lane_gates\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_test_lane_gates\") && !OutOverview.TestLaneTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"execute_next_safe_step\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"execute_next_safe_step\") && !OutOverview.ExecuteTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_runtime_verification\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_runtime_verification\") && !OutOverview.RuntimeReviewTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_gate\") && !OutOverview.GeneratedAssetReviewTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_lifecycle_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_lifecycle_gate\") && !OutOverview.GeneratedAssetLifecycleTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_animation_lifecycle_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_animation_lifecycle_gate\") && !OutOverview.GeneratedAnimationLifecycleTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"compile_generated_animation_evidence\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"compile_generated_animation_evidence\") && !OutOverview.GeneratedAnimationCompileTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_import_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_import_gate\") && !OutOverview.GeneratedAssetImportTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_quality_proof_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_quality_proof_gate\") && !OutOverview.GeneratedAssetQualityProofTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_replacement_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_replacement_gate\") && !OutOverview.GeneratedAssetReplacementTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_provider_spend_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_provider_spend_gate\") && !OutOverview.ProviderSpendTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"continue_with_placeholder_fallback\") && !OutOverview.PlaceholderTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_provider_task_gate\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_generated_asset_provider_task_gate\") && !OutOverview.GeneratedAssetProviderTaskTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_editor_queue\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_editor_queue\") && !OutOverview.QueueReviewTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"resolve_blockers\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"resolve_blockers\") && !OutOverview.BlockerTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"resolve_generated_asset\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"resolve_generated_asset\") && !OutOverview.GeneratedAssetTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"show_evidence_ledger\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"show_evidence_ledger\") && !OutOverview.EvidenceLedgerTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"start_companion_session\") && !OutOverview.StartTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"refresh_companion_status\") && !OutOverview.StatusTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"generate_work_order\") && !OutOverview.WorkOrderTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_gameplay_template_plan\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"review_gameplay_template_plan\") && !OutOverview.GameplayTemplateTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("editor_operation_count", self.cpp)
        self.assertIn("bridge_required_operation_count", self.cpp)
        self.assertIn("generated_asset_replacement_operation_count", self.cpp)
        self.assertIn("generated_animation_prompt_count", self.cpp)
        self.assertIn("generated_animation_paid_missing_gate_count", self.cpp)
        self.assertIn("generated animation prompt requirements", self.cpp)
        self.assertIn("paid-animation readiness gates", self.cpp)
        self.assertIn("%d checklist", self.cpp)
        self.assertIn("%d swap", self.cpp)
        self.assertIn("%d anim", self.cpp)
        self.assertIn("%d anim gate", self.cpp)
        self.assertIn("ActionId == TEXT(\"compile_placeholder_manifest\") && !OutOverview.PlaceholderTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"resume_companion_session\") && !OutOverview.ResumeTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"show_companion_dashboard\") && !OutOverview.DashboardTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"queue_editor_actions\") && !OutOverview.QueueTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"repair_failed_step\") && !OutOverview.RepairTargetSummary.IsEmpty()", self.cpp)
        self.assertIn("ActionId == TEXT(\"resume_companion_session\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"show_companion_dashboard\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"start_companion_session\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"refresh_companion_status\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"generate_work_order\")", self.cpp)
        self.assertIn("ActionId == TEXT(\"compile_placeholder_manifest\")", self.cpp)
        self.assertIn("OutOverview.SuggestedAction = BestWorkflowAction", self.cpp)
        self.assertIn("pending_count", self.cpp)
        self.assertIn("blocked_count", self.cpp)
        self.assertIn("recorded_count", self.cpp)
        self.assertIn("record_readiness_policy", self.cpp)
        self.assertIn("readiness_policy", self.cpp)
        self.assertIn("policy evidence", self.cpp)
        self.assertIn("Record: {1}", self.cpp)

    def test_cockpit_header_exposes_compact_workflow_actions_launcher(self) -> None:
        self.assertIn("HandleOpenWorkflowActionsClicked", self.header)
        self.assertIn("OpenCommandPaletteWithFilter", self.header)
        self.assertIn("GetCockpitWorkflowActionsText", self.header)
        self.assertIn("GetCockpitWorkflowActionsTooltip", self.header)
        self.assertIn("CockpitWorkflowActions", self.cpp)
        self.assertIn(".Text(this, &SMCPChatPanel::GetCockpitWorkflowActionsText)", self.cpp)
        self.assertIn(".ToolTipText(this, &SMCPChatPanel::GetCockpitWorkflowActionsTooltip)", self.cpp)
        self.assertIn("if (CockpitOverview.WorkflowActionCount > 0)", self.cpp)
        self.assertIn("Open {0} enabled of {1} IDE Companion workflow actions", self.cpp)
        self.assertIn("SMCPChatPanel::HandleOpenWorkflowActionsClicked", self.cpp)
        self.assertIn("OpenCommandPaletteWithFilter(TEXT(\"workflow\")", self.cpp)
        self.assertIn("workflow_actions_opened", self.cpp)
        self.assertIn("TEXT(\"Execute Next Safe Step\")", self.cpp)
        self.assertIn("TEXT(\"Repair Failed Step\")", self.cpp)
        self.assertIn("TEXT(\"Resolve Generated Asset\")", self.cpp)
        self.assertIn("TEXT(\"Show Evidence Ledger\")", self.cpp)
        self.assertGreaterEqual(self.cpp.count('TEXT("workflow")'), 12)
        self.assertIn("OutOverview.WorkflowActionCount++", self.cpp)
        self.assertIn("OutOverview.EnabledWorkflowActionCount++", self.cpp)

    def test_command_palette_kind_filters_are_exact_before_fuzzy_matching(self) -> None:
        self.assertIn("const FString ItemKind = Item.Kind.TrimStartAndEnd().ToLower()", self.cpp)
        self.assertIn("Needle == TEXT(\"workflow\")", self.cpp)
        self.assertIn("Needle == TEXT(\"asset\")", self.cpp)
        self.assertIn("return ItemKind == Needle", self.cpp)
        self.assertIn("Haystack.Contains(Needle)", self.cpp)

    def test_markdown_code_blocks_are_rendered_separately(self) -> None:
        self.assertIn("BuildMarkdownMessageBody", self.header)
        self.assertIn("AddMarkdownBlocks", self.header)
        self.assertIn("Line.StartsWith(TEXT(\"```\"))", self.cpp)
        self.assertIn("FAppStyle::GetFontStyle(\"Monospaced\")", self.cpp)
        self.assertIn("CodeBlockColor", self.cpp)

    def test_module_dependencies_cover_core_panel_features(self) -> None:
        for dependency in ("ApplicationCore", "InputCore", "AssetRegistry", "ContentBrowser", "Slate", "SlateCore"):
            with self.subTest(dependency=dependency):
                self.assertIn(f'"{dependency}"', self.build_cs)


if __name__ == "__main__":
    unittest.main()
